/** UI chrome and component labels — not portfolio narrative copy. */

export const UI_LABELS = {
  skipToContent: "Skip to content",
  hero: {
    primaryActions: "Primary actions",
    careerHighlights: "Career highlights",
    downloadCv: "Download CV",
    github: "GitHub",
    linkedin: "LinkedIn",
    contact: "Contact",
  },
  nav: {
    main: "Main navigation",
    mobile: "Mobile navigation",
    noScript: "Section navigation without JavaScript",
    portfolio: "md://portfolio",
    letsTalk: "Let's talk",
  },
  subpage: {
    backToPortfolio: "← Back to portfolio",
  },
  breadcrumb: {
    label: "Breadcrumb",
  },
  errorPage: {
    boundaryLabel: "// error_boundary",
    title: "Something went wrong",
    fallbackMessage: "An unexpected error occurred. Please try again.",
    tryAgain: "Try again",
    backHome: "Back to homepage",
  },
  footer: {
    links: "Footer links",
    privacyPolicy: "Privacy Policy",
    accessibility: "Accessibility",
    availableForWork: "Available for work",
  },
  impact: {
    tableCaption: "Capabilities by domain with summary and benchmark",
    domain: "Domain",
    summary: "Summary",
    benchmark: "Benchmark",
  },
  caseStudies: {
    keyResults: "Key results",
    context: "Context",
    problem: "Problem",
    solution: "Solution",
    results: "Results",
    architecture: "Architecture",
    technicalDetails: "Technical details",
    engineeringFocus: "Engineering focus",
    constraints: "Constraints",
    stack: "Stack",
    tradeoffs: "Trade-offs",
    performanceNotes: "Performance notes",
  },
  experience: {
    viewProject: "View project →",
    relatedProject: "Related project:",
    applications: "Applications:",
    technologiesAt: (company: string) => `Technologies at ${company}`,
    degrees: "Degrees",
  },
  education: {
    degrees: "Degrees",
  },
  contact: {
    availability: "Open to full-time, contract, and freelance",
    linksHeading: "Links",
    resumeHeading: "Resume",
    phone: "Phone",
    telegram: "Telegram",
    bookCall: "Book a call",
    bookCallHint: "15-minute intro",
    pdfDownload: "PDF download",
    emailCopied: "Email copied",
    copyEmail: (email: string) => `Copy ${email}`,
    formLegend: "Contact form",
    name: "Name",
    email: "Email",
    company: "Company",
    companyOptional: "(optional)",
    message: "Message",
    namePlaceholder: "Your name",
    emailPlaceholder: "you@company.com",
    companyPlaceholder: "Company or agency",
    messagePlaceholder: "e.g. Senior RN role, Expo stack, remote EU, start Q3…",
    toastRegion: "Form notifications",
    emailAlternative: "Prefer email, or if the form is hard to use?",
    noScriptMessage: "JavaScript is required for the contact form. Email directly instead:",
    noScriptMailSubject: "Portfolio inquiry",
    accessibilityMailSubject: "Accessibility feedback",
  },
  resume: {
    summary: "Summary",
    experience: "Professional Experience",
    skills: "Skills",
    projects: "Projects",
    education: "Education",
    languages: "Languages",
    technologies: "Technologies:",
    applications: "Applications:",
  },
  submit: {
    send: "Send message",
    sending: "Sending…",
    sent: "Message sent",
  },
  privacyConsent: "I have read the privacy policy and understand how this enquiry will be handled",
  errorBoundary: {
    unavailable: "Section unavailable",
    retry: "Retry",
  },
} as const;
