import type { Capability } from "@/lib/types";

export const CAPABILITIES: Capability[] = [
  {
    id: "mobile",
    kpi: "App Store",
    kpiSub: "Google Play",
    icon: "smartphone",
    title: "React Native mobile apps",
    desc: "Build, release, and maintain production iOS and Android apps — Firebase, push notifications, deep linking, offline storage, and App Store / Google Play releases.",
    tags: ["react-native", "expo", "typescript", "firebase", "sqlite"],
    appliedIn: "Vitadrop · Waddingtons · Amako · BetKing",
  },
  {
    id: "web",
    kpi: "React",
    kpiSub: "dashboards",
    icon: "monitor",
    title: "React web products",
    desc: "Analytics dashboards, admin panels, and customer-facing web UIs with React and TypeScript — integrated with REST and GraphQL APIs.",
    tags: ["react", "typescript", "redux", "graphql"],
    appliedIn: "Vidalytics · Education platform · Kultprosvet",
  },
  {
    id: "backend",
    kpi: "Node.js",
    kpiSub: "APIs",
    icon: "server",
    title: "Backend & APIs",
    desc: "Node.js with Express, REST, GraphQL, and GraphQL Subscriptions — MySQL and Firebase backends connected to mobile and web clients.",
    tags: ["node.js", "express", "graphql", "mysql"],
    appliedIn: "Kultprosvet · Education platform",
  },
  {
    id: "rt",
    kpi: "Real-time",
    kpiSub: "offline-first",
    icon: "network",
    title: "Live & offline features",
    desc: "WebSockets and GraphQL Subscriptions for real-time sync, offline-first field workflows, and Firebase Auth, Analytics, and Crashlytics in production.",
    tags: ["websockets", "graphql", "firebase", "offline"],
    appliedIn: "Amako · Waddingtons · Vitadrop",
  },
  {
    id: "native",
    kpi: "SDKs",
    kpiSub: "Turbo Modules",
    icon: "terminal",
    title: "Native integration",
    desc: "Turbo Modules and native host projects when React Native needs camera pipelines, UsageStats, Screen Time APIs, third-party SDKs, or platform-specific behaviour.",
    tags: ["turbo-modules", "kotlin", "swift", "ios", "android"],
    appliedIn: "Keept · Vitadrop",
  },
  {
    id: "perf",
    kpi: "Production",
    kpiSub: "support",
    icon: "gauge",
    title: "Delivery & collaboration",
    desc: "Crashlytics-driven debugging, Jest, code reviews, sprint planning, task estimation, mentoring, and stakeholder communication on team projects.",
    tags: ["crashlytics", "jest", "releases", "mentoring"],
    appliedIn: "NetGame · Elementica · Kultprosvet",
  },
];
