import type { SkillLayer } from "@/lib/types";

export const SKILL_LAYERS: SkillLayer[] = [
  {
    id: "mobile",
    layer: "Mobile · React Native",
    desc: "iOS and Android — Expo, releases, Firebase, offline storage, push, deep linking",
    projectRefs: "Vitadrop · Keept · Waddingtons · Amako",
    skills: [
      { name: "React Native", primary: true, icon: "smartphone" },
      { name: "Expo", primary: true, icon: "layers" },
      { name: "TypeScript", primary: true, icon: "code" },
      { name: "Firebase", primary: true, icon: "shield" },
      { name: "SQLite", primary: true, icon: "database" },
      { name: "Vision Camera", primary: false, icon: "eye" },
      { name: "Push Notifications", primary: false, icon: "package" },
    ],
  },
  {
    id: "frontend",
    layer: "Web · React",
    desc: "Dashboards, admin tools, and product UIs with React and TypeScript",
    projectRefs: "Vidalytics · Education platform · Kultprosvet",
    skills: [
      { name: "React", primary: true, icon: "globe" },
      { name: "TypeScript", primary: true, icon: "code" },
      { name: "Redux Toolkit", primary: true, icon: "workflow" },
      { name: "React Query", primary: false, icon: "refresh" },
      { name: "Zustand", primary: false, icon: "database" },
      { name: "GraphQL", primary: false, icon: "git-branch" },
      { name: "Postman", primary: false, icon: "wrench" },
    ],
  },
  {
    id: "realtime",
    layer: "Backend · Node.js & APIs",
    desc: "REST, GraphQL, WebSockets, and Firebase for mobile and web clients",
    projectRefs: "Kultprosvet · Waddingtons · Amako",
    skills: [
      { name: "Node.js", primary: true, icon: "server" },
      { name: "Express.js", primary: true, icon: "server" },
      { name: "WebSockets", primary: true, icon: "wifi" },
      { name: "GraphQL", primary: true, icon: "git-branch" },
      { name: "Firebase", primary: true, icon: "shield" },
      { name: "MySQL", primary: false, icon: "database" },
      { name: "MongoDB", primary: false, icon: "database" },
    ],
  },
  {
    id: "native",
    layer: "Platforms · iOS & Android",
    desc: "Store releases, Turbo Modules, and native host projects for SDK and system API access",
    projectRefs: "Keept · Vitadrop · App Store · Google Play",
    skills: [
      { name: "iOS", primary: true, icon: "cpu" },
      { name: "Android", primary: true, icon: "cpu" },
      { name: "Turbo Modules", primary: true, icon: "boxes" },
      { name: "Xcode", primary: false, icon: "wrench" },
      { name: "Android Studio", primary: false, icon: "wrench" },
      { name: "Deep Linking", primary: false, icon: "git-branch" },
    ],
  },
  {
    id: "perf",
    layer: "Production & quality",
    desc: "Crashlytics, releases, Jest, code reviews, and production support",
    projectRefs: "NetGame · Elementica · Waddingtons",
    skills: [
      { name: "Firebase Crashlytics", primary: true, icon: "shield" },
      { name: "Jest", primary: true, icon: "check" },
      { name: "App Store Connect", primary: false, icon: "package" },
      { name: "Google Play Console", primary: false, icon: "package" },
      { name: "Docker", primary: false, icon: "boxes" },
      { name: "Git", primary: false, icon: "git-branch" },
    ],
  },
  {
    id: "state",
    layer: "App state",
    desc: "Redux Toolkit, React Query, and Zustand for sync with APIs and real-time data",
    projectRefs: "Waddingtons · Vidalytics · Amako",
    skills: [
      { name: "Redux Toolkit", primary: true, icon: "workflow" },
      { name: "React Query", primary: true, icon: "refresh" },
      { name: "Zustand", primary: true, icon: "database" },
      { name: "MMKV", primary: false, icon: "database" },
    ],
  },
];
